services:
  postgres-db:
    image: postgres:16
    container_name: java-pg
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB : authorsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: