spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studydb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate.highlight_sql: true

  output.ansi.enabled: always

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info

payments:
  products-base-url: "http://localhost:${server.port}/api/products"   # куда ходим из payments
  http:
    connect-timeout-ms: 1000
    read-timeout-ms: 2000
limits:
  default-amount: 10000.00

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080