### GET USER PRODUCTS
GET http://localhost:8080/payments/products?userId=1

### GET USER BALANCE
GET http://localhost:8080/payments/balances/summary?userId=1

### GET USER PRODUCTS
GET http://localhost:8080/payments/products/999999

### GET ERROR USER PRODUCTS
GET http://localhost:8080/payments/products?userId=11

### GET ERROR USER PRODUCTS
GET http://localhost:8080/payments/products?userId=0

### CREATE NEW PAYMENT #1
POST http://localhost:8080/payments/pay
Content-Type: application/json

{
  "userId": 1,
  "productId": 1,
  "amount": 12.95
}

### CREATE NEW PAYMENT #2 WITH ERROR
POST http://localhost:8080/payments/pay
Content-Type: application/json

{
  "userId": 1,
  "productId": 2,
  "amount": 9998.99,
  "externalId": "qqq2"
}

### GET PAYMENT #1
GET http://localhost:8080/payments/1

### GET PAYMENT #2
GET http://localhost:8080/payments/2

### GET PAYMENTS BY USER
GET http://localhost:8080/payments/by-user?userId=1

